import { Menu } from './menu';


export const MENUS: Menu[] = [
    {
        id: 1,
        name: "LUNDI (Exotique)",
        entree: "Salade tropical de crevettes ",
        plat: "Poulet Coco Réunionnais, Riz",
        dessert: "Salade épicée Fraise et mangue",
        prix : 25,
        photo:  "../assets/images/rizReunion.png",
        types: ["Entrée ", "Plat ","Dessert "," 4 Personnes"],
        created: new Date(),
       
    },
    {
        id: 2,
        name: "MARDI",
        entree: "Gaspacho Andaluz",
        plat: "Boulettes de Boeuf en ragoût, Pâtes",
        dessert: "Tiramisu ",
        prix : 70,
        photo: "../assets/images/boulette.png",
        types: ["Entrée ", "Plat ","Dessert "," 4 Personnes"],
        created: new Date(),
    },
    {
        id: 3,
        name: "MERCREDI",
        entree: "Salade Grecque au concombre",
        plat: "Daurade Royale aux Pommes ",
        dessert: "Crème de Citron	",
        prix : 25,
        photo: "../assets/images/doratte.png",
        types: ["Entrée ", "Plat ","Dessert "," 4 Personnes"],
        created: new Date(),
    },
    {
        id: 4,
        name: "JEUDI",
        entree: "Cake courgette, lardons ",
        plat: "Rouelle de Porc aux oignons grelots",
        dessert: "Tarte tatin",
        prix : 25,
        photo: "../assets/images/rouette.png",
        types: ["Entrée ", "Plat ","Dessert "," 4 Personnes"],
        created: new Date(),
    },
    { id: 5,
        name: "VENDREDI",
        entree: "Pain de légumes aux couleurs",
        plat: "Gigot de sept heure",
        dessert: "Moelleux aux amandes",
        prix : 25,
        photo: "../assets/images/gigot.png",
        types: ["Entrée ", "Plat ","Dessert "," 4 Personnes"],
        created: new Date(),
    },
    {
        id: 6,
        name: "SAMEDI",
        entree: "Moules Farcies au beurre de Pastis",
        plat: "Coq au vin façon bistrot, cèpes ",
        dessert: "Ramequin fondant au Chocolat",
        prix : 35,
        photo: "../assets/images/moules.png",
        types:["Entrée ", "Plat ","Dessert "," 4 Personnes"],
        created: new Date(),
    },
    {
        id: 7,
        name: "DIMANCHE",
        entree: "Tartare de Tomates au Guacamole",
        plat: "Cocotte de Veau à la provencale ",
        dessert: "Cheese Cake à la Compote ",
        prix : 45,
        photo: "../assets/images/Cocotte.png",
        types: ["Entrée ", "Plat ","Dessert "," 4 Personnes"],
        created: new Date(),
    },
    {
        id: 8,
        name: "BOISSON",
        entree: "",
        plat: "",
        dessert: "string",
        prix : 45,
        photo: "../assets/images/Boisson.png",
        types: ["Entrée ", "Plat ","Dessert "," 4 Personnes"],
        created: new Date(),
    },
    
];



